### ISSUE TITLE
Line Breaks are not rendered

### ISSUE THREAD

**Issue by theimo1221** [zVolodymyr/docxjs#14]
While the doucment Parser detects line breaks, those are not rendered.

I already have a fix and will create PR soon

**Comment by theimo1221** [comment]
@zVolodymyr Ready for review/merge

**Comment by isocroft** [comment]
@zVolodymyr  this is a very important addition. Please review the PR by @theimo1221 as it is needed by the community of user who depend on this library like me.

**Comment by theimo1221** [comment]
I guess he fixed it himself with b8e67d692388036faea35e58a82acbea7c20a0a8
As it includes some other fixes/changes I'll need to resolve some merge conflicts in regards to my other improvements, before opening more PR's
