### ISSUE TITLE
JSZip not found on OS with case sensitity

### ISSUE THREAD

**Issue by andgest** [zVolodymyr/docxjs#25]
Hello,

I am contacting you to report a bug in your library that I have integrated into an Angular project.
On windows I have no problems, but on linux I have a message telling me that it does not find JSZip.

When I look closer, I see that the problem comes from the fact that "JSZip" is not present in node_modules, but "jszip" is.

To correct the problem, you just need to change the references to "JSZip" to "jszip" in your library.

Would it be possible to integrate this fix?

**Comment by zVolodymyr** [comment]
Should be fixed in master. Will close issue sometime later, after publishing next version of package.
