### ISSUE TITLE
Preview of image not working on firefox

### ISSUE THREAD

**Issue by andgest** [zVolodymyr/docxjs#26]
Hello,

I am contacting you to report a bug in your library that I have integrated into an Angular project.
On Firefox it is impossible to visualize images in a document.

By looking closer, I realize that the problem comes from the URL API of the browser which is not implemented in the same way on Chrome as on Firefox.

Indeed, the toString method does not return the same result:

new URL("media/image2.png", "file://docx/" + "word/").toString()
Chrome => 'file://docx/word/media/image2.png'
Firefox => 'file:///word/media/image2.png'

To correct the problem, you just need to modify the "prefix" variable in the resolvePath method of your library by replacing the value "file://docx/" with "file:///docx/";

Would it be possible to integrate this fix?

**Comment by zVolodymyr** [comment]
Fixed in master. Will close issue sometime later, after publishing next version of package.
