### ISSUE TITLE
page break

### ISSUE THREAD

**Issue by afzali** [zVolodymyr/docxjs#3]
hi,
page break didn't work properly, because i guess you didn't check the lastRenderedPageBreak.

Basically there are 3 types of breaks:
- page breaks
 - section breaks
 - lastRenderedPageBreak
thank you.

**Comment by zVolodymyr** [comment]
I failed to find any example of file with lastRenderedPageBreak. Could you provide some?

**Comment by afzali** [comment]
I solved it via this way,
1- in dom/dom.ts file add
`lastRenderedPageBreak = "lastRenderedPageBreak"`
to DomType and add 
`lastRenderedPageBreak?: boolean;`
to interface IDomRun.
2- in document-parser.ts  add
```
case "lastRenderedPageBreak":
                    result.lastRenderedPageBreak = true ;
                    break;
```
in parseRun function.
3- add and edit splitBySection in html-renderers.ts
```
...
var breakIndex = this.options.breakPages ? (p.children && p.children.findIndex(x => (<any>x).break == "page")) : -1;
                var pageBreakIndex = this.options.breakPages ? (p.children && p.children.findIndex(x => (<any>x).lastRenderedPageBreak == true)) : -1;
                
                if(sectProps || breakIndex != -1 || pageBreakIndex !=-1) {
                    current.sectProps = sectProps;
                    current = { sectProps: null, elements: [] };
                    result.push(current);
                }

                if(breakIndex != -1 && breakIndex < p.children.length - 1 || pageBreakIndex !=-1) {
                    var children = elem.children;
                    var breakIndex = (breakIndex != -1) ? breakIndex : pageBreakIndex;
...
```
and it work for me now :)
I'm sure you can write better of me, Thank you for your clean and nice code

**Comment by afzali** [comment]
> I failed to find any example of file with lastRenderedPageBreak. Could you provide some?

**Comment by afzali** [comment]
[hi.docx](https://github.com/zVolodymyr/docxjs/files/3879205/hi.docx)
example file.
