### ISSUE TITLE
picture not showing

### ISSUE THREAD

**Issue by 52flutter** [zVolodymyr/docxjs#32]
**Describe the bug**
Picture not showing see attachment

**Document**
If applicable, add *.docx document to help explain your problem.
[docxjs_issues.docx](https://github.com/zVolodymyr/docxjs/files/8448431/docxjs_issues.docx)

**Expected behavior**

**Screenshots**
docxjs
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/11569655/162360732-5b2e8a6a-f00f-4886-b5c2-8afae2ee0edb.png">
office
<img width="948" alt="image" src="https://user-images.githubusercontent.com/11569655/162360750-c1a3fb79-0be6-4a9a-9818-95fd61b332a2.png">

**Desktop (please complete the following information):**

**Additional context**
Add any other cont
[docxjs_issues.docx](https://github.com/zVolodymyr/docxjs/files/8448431/docxjs_issues.docx)
ext about the problem here.

**Comment by zVolodymyr** [comment]
Added support of VML kind images, changes commited master. Will close issue sometime later, after publishing next version of package.

P.S. VML is legacy format. I would recommend to update document editing software.

**Comment by zVolodymyr** [comment]
Fixed in version 0.1.10
