### ISSUE TITLE
support thumbnail and jump to the specified number page like pdfjs

### ISSUE THREAD

**Issue by TonyAndFriday** [zVolodymyr/docxjs#35]
as title

**Comment by zVolodymyr** [comment]
There is few points why it can't be done like in pdfjs and as result it will not be a part of library:
1) PDF format tells exactly how many pages is there and what content should be on each page. DOCX format only suggest how rendering app should split document on pages. At this point library splits pages only on page-breaks and page params changes.
2) pdfjs render PDF file as image, so it could be reused for thumbnails. This library renders DOCX into HTML, so it's wouldn't be efficient to reuse that content for thumbnails.

You could try to get result of rendering, query all `<section>`  elemets to get pages and try to build thumbnails base on it. So far it's best what you can get.

**Comment by TonyAndFriday** [comment]
thank you for your reply！
