### ISSUE TITLE
mathematical formula can't display 

### ISSUE THREAD

**Issue by heartbeat986** [zVolodymyr/docxjs#36]
version:0.1.10
example file:
[testMath.docx](https://github.com/zVolodymyr/docxjs/files/8675391/testMath.docx)

**Comment by zVolodymyr** [comment]
Partially implemented in version 0.1.11

**Comment by huashaoxu** [comment]
mathematical formula still can't display，please check this file
version:0.1.17
example file:
[testMath.docx](https://github.com/VolodymyrBaydalka/docxjs/files/12189466/testMath.docx)
